// Code generated by protoc-gen-go.
// source: cog.proto
// DO NOT EDIT!

/*
Package cog is a generated protocol buffer package.

It is generated from these files:
	cog.proto

It has these top-level messages:
	Args
	Out
	Description
	Server
	ExecuteRequest
	ExecuteResponse
	DescribeRequest
	DescribeResponse
	ValidateRequest
	ValidateResponse
*/
package cog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	// The status hasn't been processed yet.
	Status_UNKNOWN Status = 0
	// Indicates that the execution was considered a success.
	Status_SUCCESS Status = 1
	// Indicates that execution had a failure, but could be retried.
	Status_FAILURE Status = 2
	// Plugin failed and should not be retried.
	Status_FAILURE_NO_RETRIES Status = 3
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILURE",
	3: "FAILURE_NO_RETRIES",
}
var Status_value = map[string]int32{
	"UNKNOWN":            0,
	"SUCCESS":            1,
	"FAILURE":            2,
	"FAILURE_NO_RETRIES": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ArgsType int32

const (
	// The arguments will be encoded in JSON format.
	ArgsType_JSON ArgsType = 0
)

var ArgsType_name = map[int32]string{
	0: "JSON",
}
var ArgsType_value = map[string]int32{
	"JSON": 0,
}

func (x ArgsType) String() string {
	return proto.EnumName(ArgsType_name, int32(x))
}
func (ArgsType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Args struct {
	// The textual encoding of the arguments.  No matter what the type is, it must
	// be textual encoded, never binary encoded.  These arguments are always
	// translated to a binary proto in the plugin.
	ArgsType ArgsType `protobuf:"varint,1,opt,name=args_type,json=argsType,enum=cog.ArgsType" json:"args_type,omitempty"`
	// The arguments to the plugin.  This will be some textual representation of
	// the plugin's protocol buffer.
	Args []byte `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (m *Args) Reset()                    { *m = Args{} }
func (m *Args) String() string            { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()               {}
func (*Args) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Out struct {
	// The status for a run of the cog.
	Status Status `protobuf:"varint,1,opt,name=status,enum=cog.Status" json:"status,omitempty"`
	// The type of textual encoding used on the output.  This will be the same
	// as the encoding of the input.
	ArgsType ArgsType `protobuf:"varint,2,opt,name=args_type,json=argsType,enum=cog.ArgsType" json:"args_type,omitempty"`
	// The output from the cog in ArgsType textual encoding.
	Output []byte `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
}

func (m *Out) Reset()                    { *m = Out{} }
func (m *Out) String() string            { return proto.CompactTextString(m) }
func (*Out) ProtoMessage()               {}
func (*Out) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Description is used to describe a Cog. This allows us to
// auto-generate documentation and restrict usage.
type Description struct {
	// This is the owner of the Cog, which should be an email of some sort.
	Owner string `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	// This should describe what the plugin does.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Tags are used to provide key words that can be used for searching the
	// plugin data store.
	Tags []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	// This is the maximum time a plugin can take to shutdown before it receives
	// a kill -9. This defaults to 30 seconds and has a maximum value of
	// 30 minutes.  The value is recorded in seconds.
	MaxShutdownTime int32 `protobuf:"varint,7,opt,name=max_shutdown_time,json=maxShutdownTime" json:"max_shutdown_time,omitempty"`
}

func (m *Description) Reset()                    { *m = Description{} }
func (m *Description) String() string            { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()               {}
func (*Description) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Server details information about the service that called the cog.
type Server struct {
	// Represents a service endpoint that ran the cog.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	// The id of the Labor executing the plugin.
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// ExecuteRequest holds the request for a Cog to do something.
type ExecuteRequest struct {
	// The arguements to the cog.
	Args *Args `protobuf:"bytes,1,opt,name=args" json:"args,omitempty"`
	// This is the name of the real user account that is trying to run the
	// plugin. As Marmot is the actual caller, this allows the cog to
	// try and pass the user who requested the workflow. The plugin can in turn
	// pass this to remote system if it supports delegation.
	RealUser string `protobuf:"bytes,2,opt,name=real_user,json=realUser" json:"real_user,omitempty"`
	// This provides infomration about gthe server that is executing
	// the cog. This should not be set by the user, as it will just
	// be overwritten.
	Server *Server `protobuf:"bytes,3,opt,name=server" json:"server,omitempty"`
	// A token that identifies the client that started the plugin to the plugin.
	// If a request is sent without this token, the plugin panics.
	Token []byte `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecuteRequest) GetArgs() *Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecuteRequest) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

// ExecuteResponse is the response from the plugin.
type ExecuteResponse struct {
	Out *Out `protobuf:"bytes,1,opt,name=out" json:"out,omitempty"`
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExecuteResponse) GetOut() *Out {
	if m != nil {
		return m.Out
	}
	return nil
}

// DescribeRequest is a request for the plugin's description.
type DescribeRequest struct {
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// DescribeResponse holds the description of the plugin.
type DescribeResponse struct {
	Description *Description `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DescribeResponse) GetDescription() *Description {
	if m != nil {
		return m.Description
	}
	return nil
}

// ValidateRequest is used to validate the arguments of a request.
type ValidateRequest struct {
	Args *Args `protobuf:"bytes,1,opt,name=args" json:"args,omitempty"`
}

func (m *ValidateRequest) Reset()                    { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string            { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()               {}
func (*ValidateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ValidateRequest) GetArgs() *Args {
	if m != nil {
		return m.Args
	}
	return nil
}

// ValidateResponse is the response from a validate request.
type ValidateResponse struct {
}

func (m *ValidateResponse) Reset()                    { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string            { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()               {}
func (*ValidateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Args)(nil), "cog.Args")
	proto.RegisterType((*Out)(nil), "cog.Out")
	proto.RegisterType((*Description)(nil), "cog.Description")
	proto.RegisterType((*Server)(nil), "cog.Server")
	proto.RegisterType((*ExecuteRequest)(nil), "cog.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "cog.ExecuteResponse")
	proto.RegisterType((*DescribeRequest)(nil), "cog.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "cog.DescribeResponse")
	proto.RegisterType((*ValidateRequest)(nil), "cog.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "cog.ValidateResponse")
	proto.RegisterEnum("cog.Status", Status_name, Status_value)
	proto.RegisterEnum("cog.ArgsType", ArgsType_name, ArgsType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CogService service

type CogServiceClient interface {
	// Executes the cog.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Describes the cog.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// Validate takes an argument for a cog and validates the cog will
	// accept it. If not, it returns an error.
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type cogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCogServiceClient(cc *grpc.ClientConn) CogServiceClient {
	return &cogServiceClient{cc}
}

func (c *cogServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := grpc.Invoke(ctx, "/cog.CogService/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cogServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/cog.CogService/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cogServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := grpc.Invoke(ctx, "/cog.CogService/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CogService service

type CogServiceServer interface {
	// Executes the cog.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Describes the cog.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// Validate takes an argument for a cog and validates the cog will
	// accept it. If not, it returns an error.
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterCogServiceServer(s *grpc.Server, srv CogServiceServer) {
	s.RegisterService(&_CogService_serviceDesc, srv)
}

func _CogService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CogServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cog.CogService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CogServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CogService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CogServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cog.CogService/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CogServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CogService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CogServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cog.CogService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CogServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cog.CogService",
	HandlerType: (*CogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _CogService_Execute_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _CogService_Describe_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _CogService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("cog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x9b, 0xa6, 0xdb, 0x4d, 0x4e, 0x74, 0x9b, 0x3d, 0xd6, 0x25, 0x54, 0x84, 0x32, 0xde,
	0x94, 0x82, 0x8b, 0x54, 0x11, 0xbc, 0x5c, 0xd6, 0x56, 0x56, 0xa5, 0x85, 0x49, 0xab, 0x97, 0x21,
	0xdb, 0x0c, 0x31, 0xb8, 0xcd, 0xc4, 0xcc, 0xc4, 0xed, 0x3e, 0x80, 0xf8, 0x4e, 0x3e, 0x9d, 0xcc,
	0x64, 0xfa, 0xf7, 0x42, 0xbc, 0x3b, 0xe7, 0x9b, 0x9c, 0xf3, 0x7d, 0xf9, 0x4d, 0x02, 0xee, 0x92,
	0xa7, 0x97, 0x45, 0xc9, 0x25, 0x47, 0x7b, 0xc9, 0x53, 0x32, 0x81, 0xd6, 0x55, 0x99, 0x0a, 0x1c,
	0x82, 0x1b, 0x97, 0xa9, 0x88, 0xe4, 0x43, 0xc1, 0x02, 0xab, 0x6f, 0x0d, 0xce, 0x46, 0x8f, 0x2f,
	0xd5, 0xb3, 0xea, 0x74, 0xfe, 0x50, 0x30, 0xea, 0xc4, 0xa6, 0x42, 0x84, 0x96, 0xaa, 0x83, 0x66,
	0xdf, 0x1a, 0x3c, 0xa2, 0xba, 0x26, 0x39, 0xd8, 0xb3, 0x4a, 0xe2, 0x0b, 0x68, 0x0b, 0x19, 0xcb,
	0x4a, 0x98, 0x1d, 0x9e, 0xde, 0x11, 0x6a, 0x89, 0x9a, 0xa3, 0x43, 0xaf, 0xe6, 0xbf, 0xbd, 0x2e,
	0xa0, 0xcd, 0x2b, 0x59, 0x54, 0x32, 0xb0, 0xb5, 0x9b, 0xe9, 0xc8, 0x2f, 0x0b, 0xbc, 0xf7, 0x4c,
	0x2c, 0xcb, 0xac, 0x90, 0x19, 0xcf, 0xb1, 0x0b, 0x27, 0xfc, 0x3e, 0x67, 0xa5, 0xf6, 0x75, 0x69,
	0xdd, 0x60, 0x1f, 0xbc, 0x64, 0xf7, 0x90, 0xf6, 0x72, 0xe9, 0xbe, 0xa4, 0xde, 0x45, 0xc6, 0xa9,
	0x08, 0xec, 0xbe, 0x3d, 0x70, 0xa9, 0xae, 0x71, 0x08, 0xe7, 0xab, 0x78, 0x1d, 0x89, 0x6f, 0x95,
	0x4c, 0xf8, 0x7d, 0x1e, 0xc9, 0x6c, 0xc5, 0x82, 0xd3, 0xbe, 0x35, 0x38, 0xa1, 0x9d, 0x55, 0xbc,
	0x0e, 0x8d, 0x3e, 0xcf, 0x56, 0x8c, 0xbc, 0x81, 0x76, 0xc8, 0xca, 0x9f, 0xac, 0xc4, 0x1e, 0x38,
	0x2c, 0x4f, 0x0a, 0x9e, 0xe5, 0xd2, 0x84, 0xd8, 0xf6, 0x78, 0x06, 0xcd, 0x2c, 0x31, 0xf6, 0xcd,
	0x2c, 0x21, 0xbf, 0x2d, 0x38, 0x1b, 0xaf, 0xd9, 0xb2, 0x92, 0x8c, 0xb2, 0x1f, 0x15, 0x13, 0x12,
	0x9f, 0x1b, 0xa8, 0x6a, 0xd4, 0x1b, 0xb9, 0x5b, 0x1e, 0x35, 0x5f, 0x7c, 0x06, 0x6e, 0xc9, 0xe2,
	0xbb, 0xa8, 0x12, 0xac, 0x34, 0x8b, 0x1c, 0x25, 0x2c, 0x04, 0x2b, 0x35, 0x75, 0x1d, 0x42, 0x43,
	0xf2, 0x36, 0xd4, 0xb5, 0x44, 0xcd, 0x91, 0x22, 0x24, 0xf9, 0x77, 0x96, 0x07, 0x2d, 0x0d, 0xb2,
	0x6e, 0xc8, 0x4b, 0xe8, 0x6c, 0x83, 0x88, 0x82, 0xe7, 0x82, 0x61, 0x0f, 0x6c, 0x5e, 0x49, 0x13,
	0xc4, 0xd1, 0xab, 0x66, 0x95, 0xa4, 0x4a, 0x24, 0xe7, 0xd0, 0xa9, 0xa9, 0xdf, 0x6e, 0x82, 0x93,
	0x09, 0xf8, 0x3b, 0xc9, 0xac, 0x18, 0x1d, 0x72, 0xaf, 0x57, 0xf9, 0x7a, 0xd5, 0xde, 0xa5, 0x1d,
	0xdc, 0x04, 0x79, 0x05, 0x9d, 0x2f, 0xf1, 0x5d, 0x96, 0xc4, 0xff, 0xcb, 0x84, 0x20, 0xf8, 0xbb,
	0x89, 0xda, 0x79, 0xf8, 0x01, 0xda, 0xf5, 0xd7, 0x86, 0x1e, 0x9c, 0x2e, 0xa6, 0x9f, 0xa6, 0xb3,
	0xaf, 0x53, 0xbf, 0xa1, 0x9a, 0x70, 0x71, 0x7d, 0x3d, 0x0e, 0x43, 0xdf, 0x52, 0xcd, 0xe4, 0xea,
	0xe6, 0xf3, 0x82, 0x8e, 0xfd, 0x26, 0x5e, 0x00, 0x9a, 0x26, 0x9a, 0xce, 0x22, 0x3a, 0x9e, 0xd3,
	0x9b, 0x71, 0xe8, 0xdb, 0xc3, 0x2e, 0x38, 0x9b, 0xcf, 0x11, 0x1d, 0x68, 0x7d, 0x0c, 0x67, 0x53,
	0xbf, 0x31, 0xfa, 0x63, 0x01, 0x5c, 0xf3, 0x54, 0xa1, 0xcd, 0x96, 0x0c, 0xdf, 0xc2, 0xa9, 0xa1,
	0x87, 0x4f, 0x74, 0xba, 0xc3, 0x4b, 0xed, 0x75, 0x0f, 0xc5, 0x3a, 0x23, 0x69, 0xe0, 0x3b, 0x70,
	0x36, 0xcc, 0xb0, 0xbb, 0x87, 0x65, 0x4b, 0xb5, 0xf7, 0xf4, 0x48, 0xdd, 0x1f, 0xdd, 0xbc, 0xb4,
	0x19, 0x3d, 0xa2, 0x66, 0x46, 0x8f, 0xc9, 0x90, 0xc6, 0x6d, 0x5b, 0xff, 0xf7, 0xaf, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x15, 0xbb, 0xa0, 0xd9, 0x04, 0x04, 0x00, 0x00,
}
